export const countries2 = [
    {
      code: "AF",
      name: "Afghanistan",
      nameRu: "Афганистан",
      numberCode: "+93",
      length: 9,
    },
    {
      code: "AL",
      name: "Albania",
      nameRu: "Албания",
      numberCode: "+355",
      length: 9,
    },
    {
      code: "DZ",
      name: "Algeria",
      nameRu: "Алжир",
      numberCode: "+213",
      length: 9,
    },
    {
      code: "AS",
      name: "American Samoa",
      nameRu: "Американское Самоа",
      numberCode: "+1-684",
      length: 10,
    },
    {
      code: "AD",
      name: "Andorra",
      nameRu: "Андорра",
      numberCode: "+376",
      length: 6,
    },
    {
      code: "AO",
      name: "Angola",
      nameRu: "Ангола",
      numberCode: "+244",
      length: 9,
    },
    {
      code: "AI",
      name: "Anguilla",
      nameRu: "Ангилья",
      numberCode: "+1-264",
      length: 10,
    },
    {
      code: "AQ",
      name: "Antarctica",
      nameRu: "Антарктида",
      numberCode: "+672",
      length: 9,
    },
    {
      code: "AG",
      name: "Antigua and Barbuda",
      nameRu: "Антигуа и Барбуда",
      numberCode: "+1-268",
      length: 10,
    },
    {
      code: "AR",
      name: "Argentina",
      nameRu: "Аргентина",
      numberCode: "+54",
      length: 10,
    },
    {
      code: "AM",
      name: "Armenia",
      nameRu: "Армения",
      numberCode: "+374",
      length: 8,
    },
    {
      code: "AW",
      name: "Aruba",
      nameRu: "Аруба",
      numberCode: "+297",
      length: 7,
    },
    {
      code: "AU",
      name: "Australia",
      nameRu: "Австралия",
      numberCode: "+61",
      length: 9,
    },
    {
      code: "AT",
      name: "Austria",
      nameRu: "Австрия",
      numberCode: "+43",
      length: 10,
    },
    {
      code: "AZ",
      name: "Azerbaijan",
      nameRu: "Азербайджан",
      numberCode: "+994",
      length: 9,
    },
    {
      code: "BS",
      name: "Bahamas",
      nameRu: "Багамские Острова",
      numberCode: "+1-242",
      length: 10,
    },
    {
      code: "BH",
      name: "Bahrain",
      nameRu: "Бахрейн",
      numberCode: "+973",
      length: 8,
    },
    {
      code: "BD",
      name: "Bangladesh",
      nameRu: "Бангладеш",
      numberCode: "+880",
      length: 10,
    },
    {
      code: "BB",
      name: "Barbados",
      nameRu: "Барбадос",
      numberCode: "+1-246",
      length: 10,
    },
    {
      code: "BY",
      name: "Belarus",
      nameRu: "Беларусь",
      numberCode: "+375",
      length: 9,
    },
    {
      code: "BE",
      name: "Belgium",
      nameRu: "Бельгия",
      numberCode: "+32",
      length: 9,
    },
    {
      code: "BZ",
      name: "Belize",
      nameRu: "Белиз",
      numberCode: "+501",
      length: 7,
    },
    {
      code: "BJ",
      name: "Benin",
      nameRu: "Бенин",
      numberCode: "+229",
      length: 9,
    },
    {
      code: "BM",
      name: "Bermuda",
      nameRu: "Бермуды",
      numberCode: "+1-441",
      length: 10,
    },
    {
      code: "BT",
      name: "Bhutan",
      nameRu: "Бутан",
      numberCode: "+975",
      length: 8,
    },
    {
      code: "BO",
      name: "Bolivia",
      nameRu: "Боливия",
      numberCode: "+591",
      length: 8,
    },
    {
      code: "BA",
      name: "Bosnia and Herzegovina",
      nameRu: "Босния и Герцеговина",
      numberCode: "+387",
      length: 8,
    },
    {
      code: "BW",
      name: "Botswana",
      nameRu: "Ботсвана",
      numberCode: "+267",
      length: 7,
    },
    {
      code: "BR",
      name: "Brazil",
      nameRu: "Бразилия",
      numberCode: "+55",
      length: 10,
    },
    {
      code: "IO",
      name: "British Indian Ocean Territory",
      nameRu: "Британская Территория Индийского Океана",
      numberCode: "+246",
      length: 7,
    },
    {
      code: "VG",
      name: "British Virgin Islands",
      nameRu: "Британские Виргинские Острова",
      numberCode: "+1-284",
      length: 10,
    },
    {
      code: "BN",
      name: "Brunei",
      nameRu: "Бруней",
      numberCode: "+673",
      length: 7,
    },
    {
      code: "BG",
      name: "Bulgaria",
      nameRu: "Болгария",
      numberCode: "+359",
      length: 9,
    },
    {
      code: "BF",
      name: "Burkina Faso",
      nameRu: "Буркина-Фасо",
      numberCode: "+226",
      length: 8,
    },
    {
      code: "BI",
      name: "Burundi",
      nameRu: "Бурунди",
      numberCode: "+257",
      length: 8,
    },
    {
      code: "KH",
      name: "Cambodia",
      nameRu: "Камбоджа",
      numberCode: "+855",
      length: 9,
    },
    {
      code: "CM",
      name: "Cameroon",
      nameRu: "Камерун",
      numberCode: "+237",
      length: 9,
    },
    {
      code: "CA",
      name: "Canada",
      nameRu: "Канада",
      numberCode: "+1",
      length: 10,
    },
    {
      code: "CV",
      name: "Cape Verde",
      nameRu: "Кабо-Верде",
      numberCode: "+238",
      length: 7,
    },
    {
      code: "KY",
      name: "Cayman Islands",
      nameRu: "Каймановы Острова",
      numberCode: "+1-345",
      length: 10,
    },
    {
      code: "CF",
      name: "Central African Republic",
      nameRu: "Центральноафриканская Республика",
      numberCode: "+236",
      length: 8,
    },
    {
      code: "TD",
      name: "Chad",
      nameRu: "Чад",
      numberCode: "+235",
      length: 8,
    },
    {
      code: "CL",
      name: "Chile",
      nameRu: "Чили",
      numberCode: "+56",
      length: 9,
    },
    {
      code: "CN",
      name: "China",
      nameRu: "Китай",
      numberCode: "+86",
      length: 11,
    },
    {
      code: "CX",
      name: "Christmas Island",
      nameRu: "Остров Рождества",
      numberCode: "+61",
      length: 9,
    },
    {
      code: "CC",
      name: "Cocos Islands",
      nameRu: "Кокосовые Острова",
      numberCode: "+61",
      length: 9,
    },
    {
      code: "CO",
      name: "Colombia",
      nameRu: "Колумбия",
      numberCode: "+57",
      length: 10,
    },
    {
      code: "KM",
      name: "Comoros",
      nameRu: "Коморы",
      numberCode: "+269",
      length: 7,
    },
    {
      code: "CK",
      name: "Cook Islands",
      nameRu: "Острова Кука",
      numberCode: "+682",
      length: 5,
    },
    {
      code: "CR",
      name: "Costa Rica",
      nameRu: "Коста-Рика",
      numberCode: "+506",
      length: 8,
    },
    {
      code: "HR",
      name: "Croatia",
      nameRu: "Хорватия",
      numberCode: "+385",
      length: 9,
    },
    {
      code: "CU",
      name: "Cuba",
      nameRu: "Куба",
      numberCode: "+53",
      length: 8,
    },
    {
      code: "CW",
      name: "Curacao",
      nameRu: "Кюрасао",
      numberCode: "+599",
      length: 7,
    },
    {
      code: "CY",
      name: "Cyprus",
      nameRu: "Кипр",
      numberCode: "+357",
      length: 8,
    },
    {
      code: "CZ",
      name: "Czech Republic",
      nameRu: "Чехия",
      numberCode: "+420",
      length: 9,
    },
    {
      code: "CD",
      name: "Democratic Republic of the Congo",
      nameRu: "Демократическая Республика Конго",
      numberCode: "+243",
      length: 9,
    },
    {
      code: "DK",
      name: "Denmark",
      nameRu: "Дания",
      numberCode: "+45",
      length: 8,
    },
    {
      code: "DJ",
      name: "Djibouti",
      nameRu: "Джибути",
      numberCode: "+253",
      length: 6,
    },
    {
      code: "DM",
      name: "Dominica",
      nameRu: "Доминика",
      numberCode: "+1-767",
      length: 10,
    },
    {
      code: "DO",
      name: "Dominican Republic",
      nameRu: "Доминиканская Республика",
      numberCode: "+1-809",
      length: 10,
    },
    {
      code: "TL",
      name: "East Timor",
      nameRu: "Восточный Тимор",
      numberCode: "+670",
      length: 7,
    },
    {
      code: "EC",
      name: "Ecuador",
      nameRu: "Эквадор",
      numberCode: "+593",
      length: 9,
    },
    {
      code: "EG",
      name: "Egypt",
      nameRu: "Египет",
      numberCode: "+20",
      length: 10,
    },
    {
      code: "SV",
      name: "El Salvador",
      nameRu: "Сальвадор",
      numberCode: "+503",
      length: 8,
    },
    {
      code: "GQ",
      name: "Equatorial Guinea",
      nameRu: "Экваториальная Гвинея",
      numberCode: "+240",
      length: 9,
    },
    {
      code: "ER",
      name: "Eritrea",
      nameRu: "Эритрея",
      numberCode: "+291",
      length: 7,
    },
    {
      code: "EE",
      name: "Estonia",
      nameRu: "Эстония",
      numberCode: "+372",
      length: 8,
    },
    {
      code: "ET",
      name: "Ethiopia",
      nameRu: "Эфиопия",
      numberCode: "+251",
      length: 9,
    },
    {
      code: "FK",
      name: "Falkland Islands",
      nameRu: "Фолклендские острова",
      numberCode: "+500",
      length: 5,
    },
    {
      code: "FO",
      name: "Faroe Islands",
      nameRu: "Фарерские Острова",
      numberCode: "+298",
      length: 6,
    },
    {
      code: "FJ",
      name: "Fiji",
      nameRu: "Фиджи",
      numberCode: "+679",
      length: 7,
    },
    {
      code: "FI",
      name: "Finland",
      nameRu: "Финляндия",
      numberCode: "+358",
      length: 9,
    },
    {
      code: "FR",
      name: "France",
      nameRu: "Франция",
      numberCode: "+33",
      length: 9,
    },
    {
      code: "PF",
      name: "French Polynesia",
      nameRu: "Французская Полинезия",
      numberCode: "+689",
      length: 6,
    },
    {
      code: "GA",
      name: "Gabon",
      nameRu: "Габон",
      numberCode: "+241",
      length: 7,
    },
    {
      code: "GM",
      name: "Gambia",
      nameRu: "Гамбия",
      numberCode: "+220",
      length: 7,
    },
    {
      code: "GE",
      name: "Georgia",
      nameRu: "Грузия",
      numberCode: "+995",
      length: 9,
    },
    {
      code: "DE",
      name: "Germany",
      nameRu: "Германия",
      numberCode: "+49",
      length: 10,
    },
    {
      code: "GH",
      name: "Ghana",
      nameRu: "Гана",
      numberCode: "+233",
      length: 9,
    },
    {
      code: "GI",
      name: "Gibraltar",
      nameRu: "Гибралтар",
      numberCode: "+350",
      length: 8,
    },
    {
      code: "GR",
      name: "Greece",
      nameRu: "Греция",
      numberCode: "+30",
      length: 10,
    },
    {
      code: "GL",
      name: "Greenland",
      nameRu: "Гренландия",
      numberCode: "+299",
      length: 6,
    },
    {
      code: "GD",
      name: "Grenada",
      nameRu: "Гренада",
      numberCode: "+1-473",
      length: 10,
    },
    {
      code: "GU",
      name: "Guam",
      nameRu: "Гуам",
      numberCode: "+1-671",
      length: 10,
    },
    {
      code: "GT",
      name: "Guatemala",
      nameRu: "Гватемала",
      numberCode: "+502",
      length: 8,
    },
    {
      code: "GG",
      name: "Guernsey",
      nameRu: "Гернси",
      numberCode: "+44-1481",
      length: 10,
    },
    {
      code: "GN",
      name: "Guinea",
      nameRu: "Гвинея",
      numberCode: "+224",
      length: 9,
    },
    {
      code: "GW",
      name: "Guinea-Bissau",
      nameRu: "Гвинея-Бисау",
      numberCode: "+245",
      length: 9,
    },
    {
      code: "GY",
      name: "Guyana",
      nameRu: "Гайана",
      numberCode: "+592",
      length: 7,
    },
    {
      code: "HT",
      name: "Haiti",
      nameRu: "Гаити",
      numberCode: "+509",
      length: 8,
    },
    {
      code: "HN",
      name: "Honduras",
      nameRu: "Гондурас",
      numberCode: "+504",
      length: 8,
    },
    {
      code: "HK",
      name: "Hong Kong",
      nameRu: "Гонконг",
      numberCode: "+852",
      length: 8,
    },
    {
      code: "HU",
      name: "Hungary",
      nameRu: "Венгрия",
      numberCode: "+36",
      length: 9,
    },
    {
      code: "IS",
      name: "Iceland",
      nameRu: "Исландия",
      numberCode: "+354",
      length: 7,
    },
    {
      code: "IN",
      name: "India",
      nameRu: "Индия",
      numberCode: "+91",
      length: 10,
    },
    {
      code: "ID",
      name: "Indonesia",
      nameRu: "Индонезия",
      numberCode: "+62",
      length: 10,
    },
    {
      code: "IR",
      name: "Iran",
      nameRu: "Иран",
      numberCode: "+98",
      length: 10,
    },
    {
      code: "IQ",
      name: "Iraq",
      nameRu: "Ирак",
      numberCode: "+964",
      length: 10,
    },
    {
      code: "IE",
      name: "Ireland",
      nameRu: "Ирландия",
      numberCode: "+353",
      length: 9,
    },
    {
      code: "IM",
      name: "Isle of Man",
      nameRu: "Остров Мэн",
      numberCode: "+44-1624",
      length: 10,
    },
    {
      code: "IL",
      name: "Israel",
      nameRu: "Израиль",
      numberCode: "+972",
      length: 9,
    },
    {
      code: "IT",
      name: "Italy",
      nameRu: "Италия",
      numberCode: "+39",
      length: 10,
    },
    {
      code: "CI",
      name: "Ivory Coast",
      nameRu: "Кот-д'Ивуар",
      numberCode: "+225",
      length: 8,
    },
    {
      code: "JM",
      name: "Jamaica",
      nameRu: "Ямайка",
      numberCode: "+1-876",
      length: 10,
    },
    {
      code: "JP",
      name: "Japan",
      nameRu: "Япония",
      numberCode: "+81",
      length: 10,
    },
    {
      code: "JE",
      name: "Jersey",
      nameRu: "Джерси",
      numberCode: "+44-1534",
      length: 10,
    },
    {
      code: "JO",
      name: "Jordan",
      nameRu: "Иордания",
      numberCode: "+962",
      length: 9,
    },
    {
      code: "KZ",
      name: "Kazakhstan",
      nameRu: "Казахстан",
      numberCode: "+7",
      length: 10,
    },
    {
      code: "KE",
      name: "Kenya",
      nameRu: "Кения",
      numberCode: "+254",
      length: 9,
    },
    {
      code: "KI",
      name: "Kiribati",
      nameRu: "Кирибати",
      numberCode: "+686",
      length: 5,
    },
    {
      code: "XK",
      name: "Kosovo",
      nameRu: "Косово",
      numberCode: "+383",
      length: 9,
    },
    {
      code: "KW",
      name: "Kuwait",
      nameRu: "Кувейт",
      numberCode: "+965",
      length: 8,
    },
    {
      code: "KG",
      name: "Kyrgyzstan",
      nameRu: "Киргизия",
      numberCode: "+996",
      length: 9,
    },
    {
      code: "LA",
      name: "Laos",
      nameRu: "Лаос",
      numberCode: "+856",
      length: 9,
    },
    {
      code: "LV",
      name: "Latvia",
      nameRu: "Латвия",
      numberCode: "+371",
      length: 8,
    },
    {
      code: "LB",
      name: "Lebanon",
      nameRu: "Ливан",
      numberCode: "+961",
      length: 8,
    },
    {
      code: "LS",
      name: "Lesotho",
      nameRu: "Лесото",
      numberCode: "+266",
      length: 8,
    },
    {
      code: "LR",
      name: "Liberia",
      nameRu: "Либерия",
      numberCode: "+231",
      length: 7,
    },
    {
      code: "LY",
      name: "Libya",
      nameRu: "Ливия",
      numberCode: "+218",
      length: 9,
    },
    {
      code: "LI",
      name: "Liechtenstein",
      nameRu: "Лихтенштейн",
      numberCode: "+423",
      length: 7,
    },
    {
      code: "LT",
      name: "Lithuania",
      nameRu: "Литва",
      numberCode: "+370",
      length: 8,
    },
    {
      code: "LU",
      name: "Luxembourg",
      nameRu: "Люксембург",
      numberCode: "+352",
      length: 9,
    },
    {
      code: "MO",
      name: "Macau",
      nameRu: "Макао",
      numberCode: "+853",
      length: 8,
    },
    {
      code: "MK",
      name: "Macedonia",
      nameRu: "Северная Македония",
      numberCode: "+389",
      length: 8,
    },
    {
      code: "MG",
      name: "Madagascar",
      nameRu: "Мадагаскар",
      numberCode: "+261",
      length: 9,
    },
    {
      code: "MW",
      name: "Malawi",
      nameRu: "Малави",
      numberCode: "+265",
      length: 7,
    },
    {
      code: "MY",
      name: "Malaysia",
      nameRu: "Малайзия",
      numberCode: "+60",
      length: 9,
    },
    {
      code: "MV",
      name: "Maldives",
      nameRu: "Мальдивы",
      numberCode: "+960",
      length: 7,
    },
    {
      code: "ML",
      name: "Mali",
      nameRu: "Мали",
      numberCode: "+223",
      length: 8,
    },
    {
      code: "MT",
      name: "Malta",
      nameRu: "Мальта",
      numberCode: "+356",
      length: 8,
    },
    {
      code: "MH",
      name: "Marshall Islands",
      nameRu: "Маршалловы Острова",
      numberCode: "+692",
      length: 7,
    },
    {
      code: "MR",
      name: "Mauritania",
      nameRu: "Мавритания",
      numberCode: "+222",
      length: 8,
    },
    {
      code: "MU",
      name: "Mauritius",
      nameRu: "Маврикий",
      numberCode: "+230",
      length: 7,
    },
    {
      code: "YT",
      name: "Mayotte",
      nameRu: "Майотта",
      numberCode: "+262",
      length: 9,
    },
    {
      code: "MX",
      name: "Mexico",
      nameRu: "Мексика",
      numberCode: "+52",
      length: 10,
    },
    {
      code: "FM",
      name: "Micronesia",
      nameRu: "Микронезия",
      numberCode: "+691",
      length: 7,
    },
    {
      code: "MD",
      name: "Moldova",
      nameRu: "Молдова",
      numberCode: "+373",
      length: 8,
    },
    {
      code: "MC",
      name: "Monaco",
      nameRu: "Монако",
      numberCode: "+377",
      length: 8,
    },
    {
      code: "MN",
      name: "Mongolia",
      nameRu: "Монголия",
      numberCode: "+976",
      length: 8,
    },
    {
      code: "ME",
      name: "Montenegro",
      nameRu: "Черногория",
      numberCode: "+382",
      length: 8,
    },
    {
      code: "MS",
      name: "Montserrat",
      nameRu: "Монтсеррат",
      numberCode: "+1-664",
      length: 10,
    },
    {
      code: "MA",
      name: "Morocco",
      nameRu: "Марокко",
      numberCode: "+212",
      length: 9,
    },
    {
      code: "MZ",
      name: "Mozambique",
      nameRu: "Мозамбик",
      numberCode: "+258",
      length: 9,
    },
    {
      code: "MM",
      name: "Myanmar",
      nameRu: "Мьянма",
      numberCode: "+95",
      length: 9,
    },
    {
      code: "NA",
      name: "Namibia",
      nameRu: "Намибия",
      numberCode: "+264",
      length: 9,
    },
    {
      code: "NR",
      name: "Nauru",
      nameRu: "Науру",
      numberCode: "+674",
      length: 5,
    },
    {
      code: "NP",
      name: "Nepal",
      nameRu: "Непал",
      numberCode: "+977",
      length: 10,
    },
    {
      code: "NL",
      name: "Netherlands",
      nameRu: "Нидерланды",
      numberCode: "+31",
      length: 9,
    },
    {
      code: "NC",
      name: "New Caledonia",
      nameRu: "Новая Каледония",
      numberCode: "+687",
      length: 6,
    },
    {
      code: "NZ",
      name: "New Zealand",
      nameRu: "Новая Зеландия",
      numberCode: "+64",
      length: 8,
    },
    {
      code: "NI",
      name: "Nicaragua",
      nameRu: "Никарагуа",
      numberCode: "+505",
      length: 8,
    },
    {
      code: "NE",
      name: "Niger",
      nameRu: "Нигер",
      numberCode: "+227",
      length: 8,
    },
    {
      code: "NG",
      name: "Nigeria",
      nameRu: "Нигерия",
      numberCode: "+234",
      length: 9,
    },
    {
      code: "NU",
      name: "Niue",
      nameRu: "Ниуэ",
      numberCode: "+683",
      length: 4,
    },
    {
      code: "NF",
      name: "Norfolk Island",
      nameRu: "Остров Норфолк",
      numberCode: "+672",
      length: 6,
    },
    {
      code: "KP",
      name: "North Korea",
      nameRu: "Северная Корея",
      numberCode: "+850",
      length: 10,
    },
    {
      code: "MP",
      name: "Northern Mariana Islands",
      nameRu: "Северные Марианские острова",
      numberCode: "+1-670",
      length: 10,
    },
    {
      code: "NO",
      name: "Norway",
      nameRu: "Норвегия",
      numberCode: "+47",
      length: 8,
    },
    {
      code: "OM",
      name: "Oman",
      nameRu: "Оман",
      numberCode: "+968",
      length: 8,
    },
    {
      code: "PK",
      name: "Pakistan",
      nameRu: "Пакистан",
      numberCode: "+92",
      length: 10,
    },
    {
      code: "PW",
      name: "Palau",
      nameRu: "Палау",
      numberCode: "+680",
      length: 7,
    },
    {
      code: "PS",
      name: "Palestine",
      nameRu: "Палестина",
      numberCode: "+970",
      length: 9,
    },
    {
      code: "PA",
      name: "Panama",
      nameRu: "Панама",
      numberCode: "+507",
      length: 8,
    },
    {
      code: "PG",
      name: "Papua New Guinea",
      nameRu: "Папуа-Новая Гвинея",
      numberCode: "+675",
      length: 7,
    },
    {
      code: "PY",
      name: "Paraguay",
      nameRu: "Парагвай",
      numberCode: "+595",
      length: 9,
    },
    {
      code: "PE",
      name: "Peru",
      nameRu: "Перу",
      numberCode: "+51",
      length: 9,
    },
    {
      code: "PH",
      name: "Philippines",
      nameRu: "Филиппины",
      numberCode: "+63",
      length: 10,
    },
    {
      code: "PL",
      name: "Poland",
      nameRu: "Польша",
      numberCode: "+48",
      length: 9,
    },
    {
      code: "PT",
      name: "Portugal",
      nameRu: "Португалия",
      numberCode: "+351",
      length: 9,
    },
    {
      code: "PR",
      name: "Puerto Rico",
      nameRu: "Пуэрто-Рико",
      numberCode: "+1-787",
      length: 10,
    },
    {
      code: "QA",
      name: "Qatar",
      nameRu: "Катар",
      numberCode: "+974",
      length: 8,
    },
    {
      code: "RE",
      name: "Reunion",
      nameRu: "Реюньон",
      numberCode: "+262",
      length: 9,
    },
    {
      code: "RO",
      name: "Romania",
      nameRu: "Румыния",
      numberCode: "+40",
      length: 10,
    },
    {
      code: "RU",
      name: "Russia",
      nameRu: "Россия",
      numberCode: "+7",
      length: 10,
    },
    {
      code: "RW",
      name: "Rwanda",
      nameRu: "Руанда",
      numberCode: "+250",
      length: 9,
    },
    {
      code: "BL",
      name: "Saint Barthelemy",
      nameRu: "Сен-Бартелеми",
      numberCode: "+590",
      length: 9,
    },
    {
      code: "SH",
      name: "Saint Helena",
      nameRu: "Остров Святой Елены",
      numberCode: "+290",
      length: 4,
    },
    {
      code: "KN",
      name: "Saint Kitts and Nevis",
      nameRu: "Сент-Китс и Невис",
      numberCode: "+1-869",
      length: 10,
    },
    {
      code: "LC",
      name: "Saint Lucia",
      nameRu: "Сент-Люсия",
      numberCode: "+1-758",
      length: 10,
    },
    {
      code: "MF",
      name: "Saint Martin",
      nameRu: "Сен-Мартен",
      numberCode: "+590",
      length: 9,
    },
    {
      code: "PM",
      name: "Saint Pierre and Miquelon",
      nameRu: "Сен-Пьер и Микелон",
      numberCode: "+508",
      length: 6,
    },
    {
      code: "VC",
      name: "Saint Vincent and the Grenadines",
      nameRu: "Сент-Винсент и Гренадины",
      numberCode: "+1-784",
      length: 10,
    },
    {
      code: "WS",
      name: "Samoa",
      nameRu: "Самоа",
      numberCode: "+685",
      length: 5,
    },
    {
      code: "SM",
      name: "San Marino",
      nameRu: "Сан-Марино",
      numberCode: "+378",
      length: 10,
    },
    {
      code: "ST",
      name: "Sao Tome and Principe",
      nameRu: "Сан-Томе и Принсипи",
      numberCode: "+239",
      length: 7,
    },
    {
      code: "SA",
      name: "Saudi Arabia",
      nameRu: "Саудовская Аравия",
      numberCode: "+966",
      length: 9,
    },
    {
      code: "SN",
      name: "Senegal",
      nameRu: "Сенегал",
      numberCode: "+221",
      length: 9,
    },
    {
      code: "RS",
      name: "Serbia",
      nameRu: "Сербия",
      numberCode: "+381",
      length: 9,
    },
    {
      code: "SC",
      name: "Seychelles",
      nameRu: "Сейшельские Острова",
      numberCode: "+248",
      length: 7,
    },
    {
      code: "SL",
      name: "Sierra Leone",
      nameRu: "Сьерра-Леоне",
      numberCode: "+232",
      length: 8,
    },
    {
      code: "SG",
      name: "Singapore",
      nameRu: "Сингапур",
      numberCode: "+65",
      length: 8,
    },
    {
      code: "SX",
      name: "Sint Maarten",
      nameRu: "Синт-Мартен",
      numberCode: "+1-721",
      length: 10,
    },
    {
      code: "SK",
      name: "Slovakia",
      nameRu: "Словакия",
      numberCode: "+421",
      length: 9,
    },
    {
      code: "SI",
      name: "Slovenia",
      nameRu: "Словения",
      numberCode: "+386",
      length: 9,
    },
    {
      code: "SB",
      name: "Solomon Islands",
      nameRu: "Соломоновы Острова",
      numberCode: "+677",
      length: 5,
    },
    {
      code: "SO",
      name: "Somalia",
      nameRu: "Сомали",
      numberCode: "+252",
      length: 8,
    },
    {
      code: "ZA",
      name: "South Africa",
      nameRu: "Южная Африка",
      numberCode: "+27",
      length: 9,
    },
    {
      code: "KR",
      name: "South Korea",
      nameRu: "Южная Корея",
      numberCode: "+82",
      length: 9,
    },
    {
      code: "SS",
      name: "South Sudan",
      nameRu: "Южный Судан",
      numberCode: "+211",
      length: 9,
    },
    {
      code: "ES",
      name: "Spain",
      nameRu: "Испания",
      numberCode: "+34",
      length: 9,
    },
    {
      code: "LK",
      name: "Sri Lanka",
      nameRu: "Шри-Ланка",
      numberCode: "+94",
      length: 9,
    },
    {
      code: "SD",
      name: "Sudan",
      nameRu: "Судан",
      numberCode: "+249",
      length: 9,
    },
    {
      code: "SR",
      name: "Suriname",
      nameRu: "Суринам",
      numberCode: "+597",
      length: 7,
    },
    {
      code: "SJ",
      name: "Svalbard and Jan Mayen",
      nameRu: "Шпицберген и Ян-Майен",
      numberCode: "+47",
      length: 8,
    },
    {
      code: "SZ",
      name: "Swaziland",
      nameRu: "Свазиленд",
      numberCode: "+268",
      length: 8,
    },
    {
      code: "SE",
      name: "Sweden",
      nameRu: "Швеция",
      numberCode: "+46",
      length: 9,
    },
    {
      code: "CH",
      name: "Switzerland",
      nameRu: "Швейцария",
      numberCode: "+41",
      length: 9,
    },
    {
      code: "SY",
      name: "Syria",
      nameRu: "Сирия",
      numberCode: "+963",
      length: 9,
    },
    {
      code: "TW",
      name: "Taiwan",
      nameRu: "Тайвань",
      numberCode: "+886",
      length: 9,
    },
    {
      code: "TJ",
      name: "Tajikistan",
      nameRu: "Таджикистан",
      numberCode: "+992",
      length: 9,
    },
    {
      code: "TZ",
      name: "Tanzania",
      nameRu: "Танзания",
      numberCode: "+255",
      length: 9,
    },
    {
      code: "TH",
      name: "Thailand",
      nameRu: "Таиланд",
      numberCode: "+66",
      length: 9,
    },
    {
      code: "TG",
      name: "Togo",
      nameRu: "Того",
      numberCode: "+228",
      length: 8,
    },
    {
      code: "TK",
      name: "Tokelau",
      nameRu: "Токелау",
      numberCode: "+690",
      length: 4,
    },
    {
      code: "TO",
      name: "Tonga",
      nameRu: "Тонга",
      numberCode: "+676",
      length: 5,
    },
    {
      code: "TT",
      name: "Trinidad and Tobago",
      nameRu: "Тринидад и Тобаго",
      numberCode: "+1-868",
      length: 10,
    },
    {
      code: "TN",
      name: "Tunisia",
      nameRu: "Тунис",
      numberCode: "+216",
      length: 8,
    },
    {
      code: "TR",
      name: "Turkey",
      nameRu: "Турция",
      numberCode: "+90",
      length: 10,
    },
    {
      code: "TM",
      name: "Turkmenistan",
      nameRu: "Туркменистан",
      numberCode: "+993",
      length: 8,
    },
    {
      code: "TC",
      name: "Turks and Caicos Islands",
      nameRu: "Острова Теркс и Кайкос",
      numberCode: "+1-649",
      length: 10,
    },
    {
      code: "TV",
      name: "Tuvalu",
      nameRu: "Тувалу",
      numberCode: "+688",
      length: 5,
    },
    {
      code: "UG",
      name: "Uganda",
      nameRu: "Уганда",
      numberCode: "+256",
      length: 9,
    },
    {
      code: "UA",
      name: "Ukraine",
      nameRu: "Украина",
      numberCode: "+380",
      length: 9,
    },
    {
      code: "AE",
      name: "United Arab Emirates",
      nameRu: "Объединенные Арабские Эмираты",
      numberCode: "+971",
      length: 9,
    },
    {
      code: "GB",
      name: "United Kingdom",
      nameRu: "Великобритания",
      numberCode: "+44",
      length: 10,
    },
    {
      code: "US",
      name: "United States",
      nameRu: "Соединенные Штаты Америки",
      numberCode: "+1",
      length: 10,
    },
    {
      code: "UY",
      name: "Uruguay",
      nameRu: "Уругвай",
      numberCode: "+598",
      length: 8,
    },
    {
      code: "UZ",
      name: "Uzbekistan",
      nameRu: "Узбекистан",
      numberCode: "+998",
      length: 9,
    },
    {
      code: "VU",
      name: "Vanuatu",
      nameRu: "Вануату",
      numberCode: "+678",
      length: 5,
    },
    {
      code: "VA",
      name: "Vatican",
      nameRu: "Ватикан",
      numberCode: "+39-06",
      length: 10,
    },
    {
      code: "VE",
      name: "Venezuela",
      nameRu: "Венесуэла",
      numberCode: "+58",
      length: 10,
    },
    {
      code: "VN",
      name: "Vietnam",
      nameRu: "Вьетнам",
      numberCode: "+84",
      length: 9,
    },
    {
      code: "WF",
      name: "Wallis and Futuna",
      nameRu: "Уоллис и Футуна",
      numberCode: "+681",
      length: 6,
    },
    {
      code: "EH",
      name: "Western Sahara",
      nameRu: "Западная Сахара",
      numberCode: "+212",
      length: 9,
    },
    {
      code: "YE",
      name: "Yemen",
      nameRu: "Йемен",
      numberCode: "+967",
      length: 9,
    },
    {
      code: "ZM",
      name: "Zambia",
      nameRu: "Замбия",
      numberCode: "+260",
      length: 9,
    },
    {
      code: "ZW",
      name: "Zimbabwe",
      nameRu: "Зимбабве",
      numberCode: "+263",
      length: 9,
    },
  ];
  